# Generated by Django 4.0.4 on 2022-05-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('pin_passport', models.IntegerField(verbose_name='ПИН КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('number', models.IntegerField(verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('pin_passport', models.IntegerField(verbose_name='ПИН КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('number', models.IntegerField(verbose_name='Номер телефона')),
                ('problem', models.TextField(verbose_name='Причина обращения в больницу')),
            ],
        ),
        migrations.CreateModel(
            name='TreatDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Терапевт', 'Терапевт'), ('Хирург', 'Хирург')], max_length=255)),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('pin_passport', models.IntegerField(verbose_name='ПИН КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('skill', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('number', models.IntegerField(verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='MainDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('pin_passport', models.IntegerField(verbose_name='ПИН КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('skill', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('number', models.IntegerField(verbose_name='Номер телефона')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.nurse')),
                ('treat_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.treatdoctor')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpo', models.CharField(db_index=True, max_length=4, unique=True, verbose_name='ОКПО')),
                ('choice', models.CharField(choices=[('Чуй', 'Чуй'), ('Иссык-Куль', 'Иссык-Куль'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Ош', 'Ош'), ('Жалал-Абад', 'Жалал-Абад'), ('Баткен', 'Баткен')], max_length=255)),
                ('max_person', models.DecimalField(decimal_places=0, max_digits=2)),
                ('type_of_hospital', models.BooleanField(choices=[(1, 'Государственная'), (0, 'Частная')])),
                ('main_doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.maindoctor')),
            ],
        ),
    ]
