# Generated by Django 4.0.4 on 2022-05-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='CustomerName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
