# Generated by Django 4.0.4 on 2022-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindoctor',
            name='bio',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='position',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
