# Generated by Django 4.0.4 on 2022-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_maindoctor_bio_maindoctor_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindoctor',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
