# Generated by Django 4.0.4 on 2022-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_customer_subject_alter_customer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
